# Generated by Django 3.2.8 on 2021-10-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebuka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='details', max_length=300),
            preserve_default=False,
        ),
    ]
